<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Muneers-MacBook-Pro.local" failures="2" tests="13" name="runner.ProjectRunner" time="193.121" errors="0" timestamp="2020-10-07T19:01:43 EDT" skipped="0">
  <testcase classname="runner.ProjectRunner" name="runScenario" time="33.601"/>
  <system-out/>
  <testcase classname="runner.ProjectRunner" name="runScenario" time="9.793"/>
  <system-out/>
  <testcase classname="runner.ProjectRunner" name="runScenario" time="9.397"/>
  <system-out/>
  <testcase classname="runner.ProjectRunner" name="runScenario" time="19.823"/>
  <system-out/>
  <testcase classname="runner.ProjectRunner" name="runScenario" time="9.674"/>
  <system-out/>
  <testcase classname="runner.ProjectRunner" name="runScenario" time="9.831"/>
  <system-out/>
  <testcase classname="runner.ProjectRunner" name="runScenario" time="9.818"/>
  <system-out/>
  <testcase classname="runner.ProjectRunner" name="runScenario" time="17.240"/>
  <system-out/>
  <testcase classname="runner.ProjectRunner" name="runScenario" time="11.460">
    <failure message="expected [0] but found [92]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [0] but found [92]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at UI_Selenium.step_defs.TLA_6_AllTopicsTest.iVerifyThatAllTopicDashboadDoesNotContains(TLA_6_AllTopicsTest.java:82)
at ✽.I verify that AllTopic dashboad does not contains "what is your name 342344?"(file:///Users/muneerhussainy/Desktop/DynamicDevelopers/src/test/resources/features/UI/TLA_6_AllTopics.feature:34)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.ProjectRunner" name="runScenario" time="18.957"/>
  <system-out/>
  <testcase classname="runner.ProjectRunner" name="runScenario" time="9.596">
    <failure message="expected [0] but found [92]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [0] but found [92]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at UI_Selenium.step_defs.TLA_6_AllTopicsTest.iVerifyThatAllTopicDashboadDoesNotContains(TLA_6_AllTopicsTest.java:82)
at ✽.I verify that AllTopic dashboad does not contains "1234566788 1234567??"(file:///Users/muneerhussainy/Desktop/DynamicDevelopers/src/test/resources/features/UI/TLA_6_AllTopics.feature:34)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.ProjectRunner" name="runScenario" time="13.396"/>
  <system-out/>
  <testcase classname="runner.ProjectRunner" name="runScenario" time="20.535"/>
  <system-out/>
</testsuite> <!-- runner.ProjectRunner -->
